dist: xenial
language: generic
sudo: required
services:
  - docker
before_install:
  - docker pull crystallang/crystal:0.35.1
script:
  - docker run -v ${PWD}:/x -w /x crystallang/crystal:0.35.1 bash -c "/usr/bin/shards install"
  - docker run -v ${PWD}:/x -w /x crystallang/crystal:0.35.1 bash -c "/usr/bin/crystal spec"